### ISSUE TITLE
Source completions not working in Helix

### ISSUE THREAD

**Issue by augray** [astral-sh/ruff-lsp#214]
Using [helix](https://docs.helix-editor.com/title-page.html), autocompletions do not appear to be working.

To reproduce:

- install helix
- configure helix to use ruff-lsp
- execute the following:
- `hx tmp.py`
  + in editor, press `i` to enter edit mode
  + type the following:

```python
some_variable = 1
print(some_var
```

**Expected behavior**:
 I would expect to see a suggestion to complete the variable in the final line to `some_variable`

**Actual behavior**:
I see no suggestion, only an error (`Undefined name 'some_var'`)

**Configuration**:

```bash
$ ruff-lsp --version
ruff-lsp 0.0.35
$ ruff --version
ruff 0.0.284
$ hx --version
helix 23.05 (7f5940be)
$ cat ~/.config/helix/languages.toml
[[language]]
name = "python"
language-server = { command = "ruff-lsp" }
```

**Comment by zanieb** [comment]
Hi!

Ruff does not support source completions at this time — it is intended to be alongside a tool that does. Please see https://github.com/astral-sh/ruff-lsp/issues/209#issuecomment-1668849088 or https://github.com/astral-sh/ruff-lsp/issues/57#issuecomment-1399540768 for more details.

**Comment by zanieb** [comment]
Glad to see you're using Ruff in Helix though! I have been intending to pick up Helix for a while now :)

**Comment by augray** [comment]
Great, thanks for the info! For what it's worth, and for the benefit of anybody else who comes across this issue in the future: I was able to get a workable setup using `pylsp` and some special plugins. Here are some full details:

- install the following with `pip`:

```
python-lsp-ruff==1.5.1
python-lsp-server==1.7.2
```

- in your `pyproject.toml`:

```toml
[tool.pylsp.plugins.ruff]
enabled = true
```

This will cause `pylsp` to use ruff for its linting/static analysis, while `pylsp` handles all the other language server stuff. In general, it seems `pylsp` has a good number of plugins.

**Comment by aspizu** [comment]
For anyone who comes across this, Helix now supports multiple language servers. You can use ruff alongside pyright or pylsp.

Here is my `languages.toml` configuration:

```toml
[[language]]
name = "python"
roots = ["pyproject.toml"]
language-servers = ["pyright", "ruff", "pylsp"]
formatter = { command = "/home/aspizu/.config/helix/python-format.sh", args = [] }
auto-format = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pylsp]
command = "pylsp"

[language-server.ruff]
command = "ruff-lsp"
config = { settings = { organizeImports = false, run = "onSave", fixAll = false } }
```
