### ISSUE TITLE
Docstring style in Pycharm

### ISSUE THREAD

**Issue by gurland** [astral-sh/ruff-lsp#297]
I tried to run this plugin with:

```toml
[pydocstyle]
convention = "google"
``` 
but PyCharm is suggesting using Sphinx documentation, generating boilerplate like `:param:` and `:return:`

I am unsure whether it's bug or not
